services:
  - docker

#before_install:
#  - pip install --user awscli
#  - export PATH=$PATH:$HOME/.local/bin
script:
  - docker --version
  - DOCKER_API_TAG="chrwolff/udagram-api"
  - (cd udagram-api && docker build -t $DOCKER_API_TAG .)
#  - eval $(aws ecr get-login --region eu-west-1)
#  - docker tag org/web:latest 123456789000.dkr.ecr.eu-west-1.amazonaws.com/org/web:latest
#  - docker push 123456789000.dkr.ecr.eu-west-1.amazonaws.com/org/web:latest
  - DOCKER_FRONTEND_TAG="chrwolff/udagram-frontend"
  - (cd udagram-frontend && docker build -t $DOCKER_FRONTEND_TAG .)
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_API_TAG
  - docker push $DOCKER_FRONTEND_TAG
  #- kubectl apply -f deployment.yml
  #- kubectl apply -f service.yml
