apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
      - name: udagram
        image: chrwolff/udagram-api
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          value: "dbadmin"
        - name: DB_PASSWORD
          value: "Kwisatz#01"
        - name: DB_NAME
          value: "udagramchrwolffdev"
        - name: DB_HOST
          value: "udagramchrwolffdev.ct5cseid54jy.eu-central-1.rds.amazonaws.com"
        - name: DB_DIALECT
          value: "postgres"
        - name: AWS_REGION
          value: "eu-central-1"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_MEDIA_BUCKET
          value: "udagram-chrwolff-dev"
        - name: JWT_SECRET
          value: "Whazup?"
        - name: URL
          value: "http://localhost:8100"
        - name: SALT_ROUNDS
          value: "10"
        - name: IMAGE_TRANSFORM_HOST
          value: "localhost:8082"
        - name: PORT
          value: "80"
