apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api
  labels:
    app: udagram-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api
  template:
    metadata:
      labels:
        app: udagram-api
    spec:
      containers:
        - name: udagram-api
          image: chrwolff/udagram-api
          ports:
            - containerPort: 80
