apiVersion: v1
kind: Service
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  type: LoadBalancer
  selector:
    app: udagram
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
