apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      name: udagram-feed-api
      labels:
        app: udagram-feed-api
    spec:
      containers:
        - image: chrwolff/udagram-feed-api
          name: udagram-feed-api
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_USERNAME
              value: "dbadmin"
            - name: DB_PASSWORD
              value: "Kwisatz#01"
            - name: DB_NAME
              value: "udagramchrwolffdev"
            - name: DB_HOST
              value: "udagramchrwolffdev.ct5cseid54jy.eu-central-1.rds.amazonaws.com"
            - name: DB_DIALECT
              value: "postgres"
            - name: AWS_REGION
              value: "eu-central-1"
            - name: AWS_PROFILE
              value: "default"
            - name: AWS_MEDIA_BUCKET
              value: "udagram-chrwolff-dev"
            - name: JWT_SECRET
              value: "Whazup?"
            - name: URL
              value: "http://udagram-frontend:80"
            - name: PORT
              value: "8080"
            - name: ACCESS_KEY_ID
              value: AKIAV4SGLYP6N4KIF3NX
            - name: SECRET_ACCESS_KEY
              value: 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
