apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      name: udagram-feed-api
      labels:
        app: udagram-feed-api
    spec:
      containers:
        - image: chrwolff/udagram-feed-api
          name: udagram-feed-api
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: udagram-secrets
          env:
            - name: DB_DIALECT
              value: "postgres"
            - name: AWS_REGION
              value: "eu-central-1"
            - name: AWS_MEDIA_BUCKET
              value: "udagram-chrwolff-dev"
            - name: URL
              value: "http://udagram-frontend:80"
            - name: PORT
              value: "8080"
